### ISSUE TITLE
MonikAI not showing up

### ISSUE THREAD

**Issue by raxixor** [PiMaker/MonikAI#1]
Whenever I run the executable (after I make sure no other instances of it are running via Task Manager), the DDLC logo, and after that Monika, refuse to appear.

**Comment by Zaign** [comment]
Make sure to check your Anti-virus. I know Avast! was being stubborn when i tried the first few times.

**Comment by raxixor** [comment]
I only have Windows Defender (I know, it's shit. I can't be arsed to get another one). And it had no notifications happen when I launched it.

**Comment by PiMaker** [comment]
Merged to #4
