### ISSUE TITLE
[Solved]

### ISSUE THREAD

**Issue by Areaclassified** [PiMaker/MonikAI#17]
![h](https://user-images.githubusercontent.com/36488101/36510159-0b8eaeca-175a-11e8-812e-f8b50f0f83ef.PNG)
I'm trash when it comes to files and stuff but I believe I don't have a exe file to run the application help...

**Comment by bwroberts48** [comment]
You can download the exe itself directly from this link 
https://github.com/PiMaker/MonikAI/releases

**Comment by bwroberts48** [comment]
@areaclassified
You can change the title back and close the issue. That way if anyone can't find that URL they can find this thread!
