### ISSUE TITLE
can I make it a little bit bigger? 

### ISSUE THREAD

**Issue by Valllaion** [PiMaker/MonikAI#18]
I love the new mod and the work that's gonna go into it but for right now is there a way to make it slightly larger? it's kinda hard to read

**Comment by williamjcm** [comment]
Same here. Maybe 20-30 more pixels in each direction would be great.

**Comment by PiMaker** [comment]
The next version will have a slider to adjust the size to whatever you want, check back here soon(tm)!

**Comment by williamjcm** [comment]
Thank you, PiMaker!
