### ISSUE TITLE
Monika's text bubble is behind her

### ISSUE THREAD

**Issue by NovaCo1** [PiMaker/MonikAI#2]
![1capture](https://user-images.githubusercontent.com/34464332/36357842-7aaef62c-14c9-11e8-8e83-8b74d3451f6c.PNG)

**Comment by PiMaker** [comment]
My friend, you have broken reality. Honestly, I have no idea how that even happened - the order of images is hardcoded. Did the problem remain after a restart?

**Comment by PiMaker** [comment]
I hardcoded it even more. Hopefully that fixes it.
