### ISSUE TITLE
MonikAI does not react to anything

### ISSUE THREAD

**Issue by sebastianN01** [PiMaker/MonikAI#24]
I'm using windows 8.1 and Chrome. No matter what program/game or website i'm launching, MonikAI sits quietly in peace.

**Comment by bwroberts48** [comment]
Do you get any text at all (ex. Startup and idle text)? Or are only the actual reactions not working?

**Comment by sebastianN01** [comment]
I get some greetings text and talking about being alone on a disc. But nothing else

**Comment by PiMaker** [comment]
Have you started her with administrator rights?

**Comment by sebastianN01** [comment]
Yes

**Comment by PiMaker** [comment]
Merged with #25
