### ISSUE TITLE
MonikaAI doesn't react to URLs

### ISSUE THREAD

**Issue by Icep0wder** [PiMaker/MonikAI#25]
I tried both Chrome and Firefox just to be sure, neither of them works. I'm on Win10 and executing with admin rights. She reacts to processes normaly and has the idle dialougues too, but the URLs (and consequently google researches) reactions do not work.

**Comment by sebastianN01** [comment]
to add to this and my issue both at once, Yes, I do have idle dialogues when launching MonikAI, but I do not get processes dialogues as well.

**Comment by PiMaker** [comment]
Fixed with browser plugin!
