### ISSUE TITLE
Warning and Error when launching newest version.

### ISSUE THREAD

**Issue by Trilasent** [PiMaker/MonikAI#26]
![warning](https://user-images.githubusercontent.com/36512990/36646252-c8e2ce56-1a3a-11e8-9d06-40b57d5cce27.png)
![error](https://user-images.githubusercontent.com/36512990/36646253-cbcf847e-1a3a-11e8-92f2-00644d0953b9.png)

After attempting to launch the newest version of MonikAI I get these messages before the application promptly closes. Am I doing something wrong, or-?

**Comment by PiMaker** [comment]
Fixed.
