### ISSUE TITLE
Pressing the keybinds to hide Monika will make her say our default name ("User" in my case)

### ISSUE THREAD

**Issue by Sano11** [PiMaker/MonikAI#28]
When pressing Ctrl+Shift+F11, she'll say, "See you later User." Even after changing name.

**Comment by Kahdeg-15520487** [comment]
`var expression =
                                   new Expression(
                                        "Okay, see you later " + Environment.UserName +
                                        "! (Press again for me to return)", "b");`
paging Pi for this bug.

**Comment by PiMaker** [comment]
Fixed.
