### ISSUE TITLE
Graphic redesign (enhancement)

### ISSUE THREAD

**Issue by ViruSSofTer** [PiMaker/MonikAI#29]
Is it possible to make an alternate design for the sprite to make  the sitting pose in the corner over the command panel with simple animation and, maybe, looking at the mouse, input cursor, and sometimes turning the head straight to the user. I`m sure there are lots of talented artists among the fans to help with this.
The current one is classic, but alao needs to be a bit corrected - I mean, the half of head)

**Comment by williamjcm** [comment]
The sprites come from the [Monika After Story mod](https://github.com/Backdash/MonikaModDev/). This is why part of Monika's hair is "off-screen".

However, it's true that MonikAI could stop looking at the screen, and try looking at the cursor *à la* `xeyes` once in a while.

**Comment by PiMaker** [comment]
While I like the idea, the graphic system currently is way underdeveloped for this task as I'm not a great designer. I like the idea, so I'm keeping this open for people to see however.

**Comment by BlasterShip7** [comment]
Not sure if this is helpful but there is a live wallpaper of Monika blinking, only available on steam.
http://steamcommunity.com/sharedfiles/filedetails/?id=1205278578

**Comment by ViruSSofTer** [comment]
BTW, as it is stated in MonikaAfterStory dev blog, the out-of-frame part is already drawn (as for the update from january the 29th...)

**Comment by williamjcm** [comment]
I can confirm what ViruSSofTer said.

**Comment by ViruSSofTer** [comment]
A little bit of animation test for concept I said about higher. It`s pretty rough, but may look much better with good artist (if one ever appears for help).
Don`t pay attention to the pixel style - it`s the first random image I found similar to the pose I needed))

**Comment by ViruSSofTer** [comment]
Looked through the current AfterStory files and grabbed some of full-drawn sprites. Here`s the archive with them to replace the corresponding sprites in the app (making this myself seems to need some sort of special access, so I just leave it here)

[MonikAI.zip](https://github.com/PiMaker/MonikAI/files/1935594/MonikAI.zip)

Also added 2.png sprites for sleeping pose for some existing dialogues and my another behaviour suggestion.

**Comment by PiMaker** [comment]
Fixed in newest release!
