### ISSUE TITLE
Issue with random responses.

### ISSUE THREAD

**Issue by williamjcm** [PiMaker/MonikAI#30]
MonikAI is supposed to choose a response among potential ones when launching applications, but doesn't.

For example, launching `ddlc.exe` always ends with MonikAI saying "Same old story? Eh?"
Other responses don't show up, even after repeated launches of `ddlc.exe`.

Another example, launching `vlc.exe` always results in the "I love listening to music." response, and never the "Oh? What are we gonna watch?" one.

**Comment by PiMaker** [comment]
Fixed!

**Comment by williamjcm** [comment]
Thank you very much, PiMaker!
