### ISSUE TITLE
Having Monika AI opened causes Chrome to freeze repeadetly

### ISSUE THREAD

**Issue by Icep0wder** [PiMaker/MonikAI#31]
Noticed this started happening since i downloaded the new version, everything else on my laptop runs fine while it's active, expcept for chrome; this results being expecially annoying when watching youtube videos or any other kind of video in general. I didn't test it with Firefox. I even have the Potato mode activated.

**Comment by PiMaker** [comment]
This is currently unavoidable because Chrome has no native way of obtaining the URL from the address bar. For some people it works, for some it doesn't. Try updating chrome to the latest version, if you're not using that already.
