### ISSUE TITLE
[Question] Compatibility with MAS

### ISSUE THREAD

**Issue by TinyInternetTree** [PiMaker/MonikAI#33]
So this is probably a stupid question but I saw this mod mentioned a lot on the MAS page. So, I was curious as to whether this mod is compatible with MAS? If not, are there future plans to make it compatible with MAS? I was just wondering because MonikAI is mentioned quite a lot over there.

**Comment by williamjcm** [comment]
It's not a mod. It's a separate program.

However, MAS has an easter egg if MonikAI's running.
