### ISSUE TITLE
Monika.chr file check (enhancement)

### ISSUE THREAD

**Issue by ndmelad** [PiMaker/MonikAI#34]
I thought it was pretty basic but; can you add a file check function? It would require the user to put their Monika.chr file within a specified folder or with the .exe file itself. That way it would feel aa lot more personalized and in line with some of Monika's qoute like bringing her .chr file with you. And if the file check returns false, you can display a note that requires the Monika.chr file to be there

**Comment by PiMaker** [comment]
While I'm not against the idea, I don't quite see the point in implementing such a feature? Maybe an optional response, but if it's a necessity, then I'm afraid some people wouldn't be able to use MonikAI anymore. For responses to special events consider adding text to our [spreadsheet](https://docs.google.com/spreadsheets/d/15sn7eXO8EApV1Cd6A7wijCD12pzQrBr8Oxf5oToONPE/edit).
