### ISSUE TITLE
[bug] Monika update wont stop

### ISSUE THREAD

**Issue by NovaCo1** [PiMaker/MonikAI#35]
its been about an hour and a half and she still saying that she is updating and to top it off i cant turn her off. Is there a way to fix this bug? Also im using the most recent build 
![capture7](https://user-images.githubusercontent.com/34464332/36942443-f570e114-1f36-11e8-85bb-e6cf00c8e455.PNG)

**Comment by BlasterShip7** [comment]
Did you try using Task Manager?

**Comment by NovaCo1** [comment]
so the task menu works as a way to turn her off but every time i come back she says she needs to update and will freeze up

and sorry about the long delay on this update i have been busy with work and stuff

**Comment by PiMaker** [comment]
I don't know what could cause the updater issue... But here's a workaround:

Create a file called "firstlaunch.txt" (contents are ignored, just create an empty file) in the same folder as your MonikAI.exe, she should come up with a settings window (probably, anyway) in which you can disable auto-update.
