### ISSUE TITLE
Regarding update 0.3

### ISSUE THREAD

**Issue by sebastianN01** [PiMaker/MonikAI#36]
It seems like "short" interval for dialogues is actually pretty long, feels like it should be the new "regular" though.

Also, everything else seems to be alright at this point.. the only problem i see is that MonikAI doesn't react to links written into chrome browser. She does react when opening the browser up though.

**Comment by PiMaker** [comment]
The issue with chrome lies within the browser itself.

**Comment by sebastianN01** [comment]
soo no chances?
