### ISSUE TITLE
Placement (bug)

### ISSUE THREAD

**Issue by ndmelad** [PiMaker/MonikAI#37]
When starting MonikAI on default setting(right side) she does not show up on screen; increasing the size would show that she is far off the lower right part of the monitor. Swapped to left and she would be too low. When I used the manual placement she isn't centered on my mouse but on it's lower right. after placing her on the corner the 'hit box' for her fading effect is where I clicked with the mouse, not on her window.

**Comment by PiMaker** [comment]
Merged with #40
