### ISSUE TITLE
[Suggestion] Wait time drop-down improvement.

### ISSUE THREAD

**Issue by williamjcm** [PiMaker/MonikAI#38]
In the settings UI, the "Wait time between idle dialogue?" drop-down menu uses labels (from "Very Short" to "Very Long").

What I'm suggesting is the addition of the actual wait time to those labels.

For example:
The "Very Short" option has a wait time between 30 and 120 seconds. The new label could become "Very Short (30 to 120s)".

**Comment by PiMaker** [comment]
Implemented!
