### ISSUE TITLE
Update Error Message When Starting MonikAI. (Also typos and capitalization errors)

### ISSUE THREAD

**Issue by Trilasent** [PiMaker/MonikAI#39]
Not quite sure what the problem could be, but just in case it can be hotfixed, here's what I've been getting since yesterday whenever MonikAI starts up. Everything functions as normally, however she just can't update on startup.

Also, the Antarctica dialogue has some typos, as well as one of the 'full screen' dialogues.
First one, "You know what ironic...Ants don't live in Antartica." should be corrected to, "You know what's ironic? Ants don't live in Antarctica."

The 'full screen' dialogue just has some capitalization errors with some I's being lowercase (i) instead of capitalized.

![63586ffff3b68776c1e54d309be3f479](https://user-images.githubusercontent.com/36512990/37066403-e244eb22-216a-11e8-8189-b9fe172d8bf1.png)

**Comment by PiMaker** [comment]
The update thing is weird, are you maybe running on a shared IP? GitHub (what MonikAI uses for downloads) might be rate limiting you.

For typos, visit the [Spreadsheet](https://docs.google.com/spreadsheets/d/15sn7eXO8EApV1Cd6A7wijCD12pzQrBr8Oxf5oToONPE/edit).
