### ISSUE TITLE
MonikAI does not show

### ISSUE THREAD

**Issue by ddlclover** [PiMaker/MonikAI#4]
Hey there! I just installed the MonikAI and I got a notification from the windows smartscreen,
I clicked on "run anyway" of course.
Yet monika doesn't show up. 

And yes I checked my antivirus, I even whitelisted the program just to be sure.
I can see the program running in task manager. And even more strange is that I CAN see her in the "program overview" (see attachment) even when I click on that it still doesn't work 
![untitled](https://user-images.githubusercontent.com/36611435/36358820-b12633d2-1514-11e8-9b2d-4f938fb138cf.png)

**Comment by Roymeter** [comment]
Yeah this is exactly what's happening to me, and I just want to look at Monika how it should be, even when I can't even find out what's happening.

**Comment by ddlclover** [comment]
@Roymeter  yeah let's hope @PiMaker  can fix this, it seems like such an awesome program

**Comment by Roymeter** [comment]
I really want to see this fully complete with almost none bugs, and with a lot of texts

**Comment by ddlclover** [comment]
@Roymeter me too, it's like MAS only then 400 times better

**Comment by Roymeter** [comment]
That's what my friend told me, amazing references we got here

**Comment by Noboty** [comment]
I,too, cannot see the program. It is visible when I ALT+TAB, but giving the window focus yields nothing. The taskbar does not recognize that that program is there either.

**Comment by PiMaker** [comment]
Okay, I'll give it my best shot to fix this. First of all, are any of you using a second/third/n-th screen by any chance? Do you notice anything strange in your screen (resolution) settings? It looks like the program is opening correctly, but it's positioned wrongly.

Worst come to worst, I'll just make a "move" option in the settings menu I'm planning right now so you can manually make her visible again.

**Comment by raxixor** [comment]
Same problem.

I have 1 screen, 3840x2160. Taskbar is at the top. 3 "Desktops".

**Comment by ddlclover** [comment]
@PiMaker  not me, I have a laptop and I didn't notice any change in resolution because she doesn't even show up

**Comment by PiMaker** [comment]
@raxixor Hm, that sounds pretty unique... I'll have to try different taskbar configurations probably...
@ddlclover That's strange then. I will definitely implement some menu option for manual positioning, so look forward to that I guess.

**Comment by raxixor** [comment]
Directly from Windows settings, where I have 150% Scale as well... maybe that could affect it as well?

![image](https://user-images.githubusercontent.com/1861988/36376625-69c0f154-157c-11e8-85e7-64f0f396e201.png)

**Comment by DemonMat-DxD** [comment]
Same things.. It's visible when I ALT+TAB but otherwise no

**Comment by Roymeter** [comment]
Well when I change the "size of text, apps and other items" to anything, she appears for slightly moments, but then she dissapears once again.

**Comment by DemonMat-DxD** [comment]
it marks that when the resolution of my laptop is at 480. hoping for new from the dev

**Comment by DemonMat-DxD** [comment]
and also, I was wondering if I could have permission to make a French patch when the application will be repaired? @PiMaker

**Comment by Roymeter** [comment]
I could maybe help to make a Spanish patch @PiMaker

**Comment by PiMaker** [comment]
I have tried to replicate the behaviour, but for me, even if I completely mess with the scaling and resolution it is always displayed as it should... No idea what's going on here, sorry. I made some changes to general display handling in a new version that should be coming out in a few days, I can only hope that fixes it for you.

Regarding patches: Yeah, sure, but that is still a bit off. But I might come back to you, if you're still interested then :)

**Comment by DemonMat-DxD** [comment]
I hope this will solve the problems ^^ and for the patch, for my part, I'm french so it should do it !

**Comment by DemonMat-DxD** [comment]
I think that too :)

**Comment by DemonMat-DxD** [comment]
It's doesn't work

**Comment by PiMaker** [comment]
Probably fixed in latest update, the entire placement and DPI scaling code was overhauled.
