### ISSUE TITLE
Hitbox is off when manually placing Monika

### ISSUE THREAD

**Issue by SergeantLagsalot** [PiMaker/MonikAI#40]
When manually placing Monika, the hitbox doesn't completely follow her. It places itself the bottom of it is at her eyes.

Red line is where she starts fading. Blue is where she reach maximum fade.
![image](https://user-images.githubusercontent.com/37139509/37083576-36363454-21f0-11e8-9e28-864e9dba8248.png)

**Comment by PiMaker** [comment]
Fixed in newest release!
