### ISSUE TITLE
Unable to get past the intro...

### ISSUE THREAD

**Issue by Olliesama** [PiMaker/MonikAI#42]
Monika freezes at the end of the intro for me, if starting up for the first time she'll reach the end and then immediately start another intro.
I say it freezes because Monika no longer does anything, the text box is still open and she won't close by herself. I have to forcefully end the task in the task manager.
I've tried deleting the MonikAi folder in the Roaming folder, I've re downloaded it multiple times and the latest update sadly doesn't work.
I'm running it on Windows 7 and as an Administrator...Not really sure what else I can try.

**Comment by PiMaker** [comment]
Try deleting the `C:\Users\<username>\AppData\Local\MonikAI` folder (Note the "local" part instead of "Roaming").

**Comment by Olliesama** [comment]
Unfortunately it didn't work.
I got rid of both at once to be certain.

**Comment by Olliesama** [comment]
So something in between the updates is causing it.
I recently tried deleting all registry entries that have anything with "MonikAI" in the end to no avail (After backing the registry up)

**Comment by PiMaker** [comment]
MonikAI does not save anything to the registry. You can however try a full reset by creating a file called `firstlaunch.txt` next to MonikAI.exe (contents of the file don't matter) and then starting MonikAI. This will delete your settings and overwrite them with the default values as well as skip auto-update for the version currently installed.

**Comment by Olliesama** [comment]
Unfortunately that didn't work...
I also tried it after deleting both the roaming and local MonikAI file.

Not sure why the first MonikAI release version works and the latest doesn't...

**Comment by Olliesama** [comment]
I should note that I tried it on another account on the computer too, with the same result. :/
