### ISSUE TITLE
Adjustable fade boundaries?

### ISSUE THREAD

**Issue by Trilasent** [PiMaker/MonikAI#43]
Would it be possible to have the fade boundaries be adjustable to be as close to her as possible? I'd love to be able to have her window at max size and have my mouse in the center of my screen without having her faded out all the way.

![untitled](https://user-images.githubusercontent.com/36512990/37160926-f48b6606-22b6-11e8-8539-209d68a92f99.png)

Something like this perhaps? 

Apologies if this is a nitpick type of thing, it's something that's been on my mind for the last couple of days.

**Comment by Trilasent** [comment]
Or even possibly disabling the fade altogether?

**Comment by williamjcm** [comment]
Or maybe an option to set a maximum opacity, so that she would always be partially faded.

**Comment by PiMaker** [comment]
Fixed in newest version! Redownload from http://monik.ai if the auto-updater doesn't do the trick

**Comment by Trilasent** [comment]
I'm not noticing much of a difference? Her window still starts fading when my mouse is a tiny bit to the right of the center of the screen?

**Comment by PiMaker** [comment]
Well, it fades around an imaginary rectangle drawn around the entire application (including the table at the bottom). But it should no longer erroneously fade on high DPI screens. Maybe I misunderstood your issue :/

**Comment by williamjcm** [comment]
Trilasent wants the rectangle to be smaller.

**Comment by Trilasent** [comment]
What I was requesting was having the boundaries decreased to just right around Monika herself, or more desireably an option to disable the fading at all so that she’s 100% visible on screen at all times if desired. :)
