### ISSUE TITLE
Chrome freezing up while she's available

### ISSUE THREAD

**Issue by Eismis-Gravas** [PiMaker/MonikAI#48]
Noticed that when Monika's active my chrome tends to freeze up for a second or two every time Monikas acitivity in task manager spikes up. 

I've had task manager open for a few minutes and saw that every once in a while Monika's task goes above 0% (most of the time it will sit at 0%, but occasionally will go up to 0.6-3.2%) of cpu use and during that time, chrome would freeze up and drop its cpu usage down to 0%. This occurs both when she's happily sitting in the corner or hidden with F11, both with Potato PC enabled and it being disabled, and the only way to stop this freezing every 5-10 or so seconds is to sadly shut her down.

Response time settings didn't make a change since I thought maybe she's looking for something relatable to talk about, but it didn't seem to have an effect.

The size of her also has no change (don't know why I thought to test it out).

Would be nice if You had any possible solutions or ideas on what to do on my end, since I'd really like to enjoy her pressence outside the space classroom.

**Comment by PiMaker** [comment]
This is a known issue that a lot of people with Google Chrome have... Sadly, I have no idea why it happens. If anyone has an idea, shoot me a pull request or something, for now I'm just leaving this here. Sorry!

**Comment by PiMaker** [comment]
Fixed with browser plugin!
