### ISSUE TITLE
Small Visual Suggestions 

### ISSUE THREAD

**Issue by Buy1Get1** [PiMaker/MonikAI#49]
![screenshot 17](https://user-images.githubusercontent.com/35557096/38126437-a3f99fb4-33be-11e8-8789-76818de89378.png)
^ Monika's head is cut off at the top. 

Second, could there be an option for darker text? The white text is a little tough to read.
Thanks for the awesome program.
I hope this helps.

**Comment by williamjcm** [comment]
The cut sprite is normal. The assets come from the Monika After Story mod for DDLC, which have the same "issue".

And about the darker text: maybe some kind of outline like in DDLC would be better. Unless that can't be done in plain C#.

**Comment by Buy1Get1** [comment]
https://stackoverflow.com/questions/4200843/outline-text-with-system-drawing
^
new GraphicsPath (creates an empty GraphicsPath)
GraphicsPath.AddString (the GraphicsPath object now represents the outline of the text)
Graphics.DrawPath (draws the outline in any Pen you want)
I hope this helps.

**Comment by PiMaker** [comment]
Sprite has been fixed in latest update! Outlining text in WPF is really difficult, so that may be a task for another time.
