### ISSUE TITLE
5k Monitor, Monika not showing up

### ISSUE THREAD

**Issue by PapaJeff** [PiMaker/MonikAI#51]
Monika isn't showing up tried making the window bigger and "manually moving the window" to try to get her onto view but still not showing up. I use an 27 inch 5k Imac that has bootcamp running windows, i think it may have something to do with the resolution or size.

**Comment by PiMaker** [comment]
Different monitor sizes and scales can royally mess up MonikAI. Manual placement mode usually fixes it, if it doesn't, I'm sorry, but that's too specific of an issue for me to really look into :/
