### ISSUE TITLE
Options won't open and Monika won't fade out when cursor is on Monika

### ISSUE THREAD

**Issue by jericjan** [PiMaker/MonikAI#53]
When I press Ctrl+Shift+F10, nothing happens. When I place my cursor on Monika, nothing happens. Even Ctrl+Shift+F12 doesn't close Monika.

**Comment by PiMaker** [comment]
That means MonikAI is fully stuck. Try reinstalling the program from http://monik.ai , strangely enough, that seemed to fix it for some people.

**Comment by PiMaker** [comment]
I'm closing this in favor of #54
