### ISSUE TITLE
Monika Freezes after intro

### ISSUE THREAD

**Issue by Tycitron6000** [PiMaker/MonikAI#54]
Okay, so when you start up Monika for the first time, she does her usual intro, and once she finishes it, she IMMEDIATELY goes on to do the "Welcome Back (Player Name)!" texts, and when she finishes, she just freezes there with the dialogue still open and doesn't do anything else, and you cant close her without going into task manager and ending her process, ive tried re-downloading and doing the "firstlaunch.txt" Thing, and its still doing it, anyway to fix this? Im running windows 8 as an administrator. (Im sorry if somebody already said this somewhere, i just really want to get this masterpiece to work!)

**Comment by Olliesama** [comment]
I got the same thing man. No fix yet.

**Comment by Tycitron6000** [comment]
Yeah i guess we'll have to wait for another release or for somebody to find a fix..

**Comment by Tycitron6000** [comment]
Good news, it works! yaay! thank you for fixing it! hopefully it stays this way though!
