### ISSUE TITLE
Fade region doesn't align with graphical representation.

### ISSUE THREAD

**Issue by TheBlackReaper98** [PiMaker/MonikAI#56]
Monika fades away when the cursor is around the center of the screen rather than when it is above her, thus she can get in the way. This problem can also be seen when manually placing Monika as she does not move under the curser, but rather below and to the right by a fair margin. While I am submitting an issue I might as well also bring up the fact that the top of her head is cut off, and it would be great if that to could be fixed.

Edit: The first issue was solved simply by restarting my computer.

**Comment by williamjcm** [comment]
The sprites came from the Monika After Story mod, back when the top of the head was cut as well.

As for your other issues, what is your scaling setting ? That could be the issue.
(If you're on Windows 10: Settings -> System -> Display -> Scaling)

**Comment by TheBlackReaper98** [comment]
@williamjcm While yes, when viewing Monika in-game the top of her head is cut off, however, when going into the modded game files you will find that the top of her head is fully intact.

**Comment by williamjcm** [comment]
There was a time where Monika's head was cut in MAS too. Ryuse fixed that relatively recently, though.
