### ISSUE TITLE
"Monik.AI has stopped working"

### ISSUE THREAD

**Issue by enderflandre** [PiMaker/MonikAI#59]
Every time I load her, I get a pop-up saying "Monik.AI has stopped working" and the app closes. I have Windows 8, could that be the problem? Or is it something else? Sorry for being a little dumb with computers, help is very appreciated. Thank you!

**Comment by williamjcm** [comment]
Windows 8 or Windows 8.1 ?

If it's the former, please upgrade to 8.1, because 8 has major compatibility issues.

However, while that might not be your issue, it's worth a try.
