### ISSUE TITLE
[Suggestion] Playing game together with Monika.

### ISSUE THREAD

**Issue by afghan26** [PiMaker/MonikAI#62]
I think it would be really cute if we can play a game together with Monika. It's just like in Monika After Story, but instead the game came from our own directory. It doesn't have to be a big game, it can be a simple game like Pac-man or Tetris. Or maybe something a little more advanced like the old Final Fantasy or Undertale. (is Undertale a bit too much?)

Sorry if i'm hard to understand. I'm not a native speaker after all (lol).

**Comment by PiMaker** [comment]
MonikAI is supposed to be a passive extension. For interaction, MAS (as you mentioned) is a good alternative!
