### ISSUE TITLE
[Suggestion] Some game  reactions

### ISSUE THREAD

**Issue by CoffeeJackaboy** [PiMaker/MonikAI#68]
Warframe : "Wake up Tenno"
                   "It's farming time"

Assassins creed : I dont have any idea for this one i just like the games (ALL OF THEM)

Tomb raider : "I think i might get jealous."
                       "Maybe I can replace her character with mine "

Dark souls : "Please dont punch the screen"

Sonic Mania (or any other Sonic game) : "Gotta go fast!"

Batman Arkham (something) : "I'M BATMAN!"

The wolf among us : "Are you the big bad wolf ?"
                                  ''AUUUUU(wolf sounds)"

Mass Effect : "Grettings commander Shepard"

Nier Automata : "Ahem!.. (user)"

CS:GO : "(insert russian words here)"
              "Fire in the hole"

Fortnite : "Dabs"

Overwatch : "Cheers love the chavalrys here"
                     "DIE DIE DIE DIE DIE DIE DIE DIE DIE DIE DIE "

Prey : "Nothing is what you think"

Superhot : "SUPER HOT"

Dishonored : "CORVO"

    I know that they are not the best ideas and i know that my english is bad but a least i tried

**Comment by PiMaker** [comment]
Join our Discord over on http://discord.monik.ai/ and check out the channel "dialogue-guide"! You can contribute as much text as you want :)

... That said, there is currently no fixed schedule when I will implement new text.
