### ISSUE TITLE
Development MonikAI

### ISSUE THREAD

**Issue by EvolutionPixG** [PiMaker/MonikAI#76]
Is further development planned or is the MonikAI project abandoned forever?

**Comment by PiMaker** [comment]
As it stands it's abandoned. Although it is open source, so if anyone's up to continue it...

**Comment by EvolutionPixG** [comment]
> 
> 
> As it stands it's abandoned. Although it is open source, so if anyone's up to continue it...

I understand. But do you plan to continue developing the project in the future?

**Comment by PiMaker** [comment]
No

**Comment by evpix** [comment]
> 
> 
> No

OK. Then good luck with other projects!
