### ISSUE TITLE
Why can't I visit monik.ai?

### ISSUE THREAD

**Issue by misaka19465** [PiMaker/MonikAI#83]
Whether visit it out of the Great Firewall or visit it in China Net. Is the server stopped?

**Comment by TheDevilOfJesters** [comment]
looks like the domain registration ran out (https://www.whois.com/whois/monik.ai)  let's hope no one buys the domain before the current maintainer can get it and set the site back up

**Comment by PiMaker** [comment]
The domain was not held by me back in the day, but by one of the community members on our Discord. They stopped paying for it a while back ¯\\_(ツ)_/¯

Anyway, I updated the Readme to no longer point to that domain, as I will not repurchase it. You can still download from the GitHub releases directly, as always.
