### ISSUE TITLE
I want to register a domain for MonikAI

### ISSUE THREAD

**Issue by misaka19465** [PiMaker/MonikAI#84]
The domain was not held by me back in the day, but by one of the community members on our Discord. They stopped paying for it a while back ¯\\_(ツ)_/¯

Anyway, I updated the Readme to no longer point to that domain, as I will not repurchase it. You can still download from the GitHub releases directly, as always.

_Originally posted by @PiMaker in https://github.com/PiMaker/MonikAI/issues/83#issuecomment-706547398_

monik.ai is too expensive that I can't pay for it, but I can register a domain called monikai.com and use for MonikAI for free. If MonikAI need it, plz tell me and I'll take the domain.

**Comment by PiMaker** [comment]
I really appreciate the offer, but I believe MonikAI is rather past its prime, and a new domain wouldn't really help.

Better go spend your money on something else :)
