### ISSUE TITLE
Really dumb question

### ISSUE THREAD

**Issue by vgamer1991** [PiMaker/MonikAI#91]
How do I open up the menu? I told Monika to call me something other than my desktop name (which isn't even what it should have been in the first place - the desktop name, that is!) and she did...until I moved the MonikAI.master folder to a more appropriate place. Then of course I had to start over as if it was freshly installed but I forgot to tell her what to call me this time, so she's using the desktop name. I forgot how to open the menu though. Hyelp!

**Comment by PiMaker** [comment]
`CTRL-SHIFT-F10` -> Settings
`CTRL-SHIFT-F11` -> Hide/Show
`CTRL-SHIFT-F12` -> Exit
