### ISSUE TITLE
cant get monika to go away

### ISSUE THREAD

**Issue by nmmmxx** [PiMaker/MonikAI#93]
i cant access the file, and you need to close it to be able to delete it. i've been trying to get her away for a while now. when i restart, she just comes back. how do i stop her from getting back? i cant find any settings i have that makes her do that.

**Comment by PiMaker** [comment]
CTRL-SHIFT-F10
CTRL-SHIFT-F11
CTRL-SHIFT-F12
...all do things. Close, Hide, Open Menu.

Worst case: Open task manager, close MonikAI and delete the .exe file.
